### ISSUE TITLE
Remember Filters

### ISSUE THREAD

**Issue by eHanus** [Gerren/Playnite-FilterMaster#3]
It would be a nice option to have the filters remembered after switching to another view in PlayNite. So when coming back from a search you can pick up with a different item that was found.

**Comment by Gerren** [comment]
Hi. Oh yeah, I totally understand. I've made this modification by the other extension too.

I will look into that.

**Comment by Gerren** [comment]
Hi there, the extension now remembers the state while switching between different views of playnite, e.g. game details in your library.

Resolved in 1.04
