### ISSUE TITLE
[Feature request] Ability to save applied combination of filters to conveniently re-apply later

### ISSUE THREAD

**Issue by Kookiness** [Gerren/Playnite-FilterMaster#5]
This addon is incredible, thank you so much for developing and releasing it!

If time permits, I was wondering if you might be interested in considering developing a feature to save a combination of applied filters, so that multiple searches can be saved (maybe in a dropdown list), and easily applied again later.

I know the built-in Playnite filters do have a feature like this already, but... your filters are more comprehensive! :)

**Comment by Gerren** [comment]
Hi there,

that sound completely reasonable, and I might look into that. I might use that too, after all :)

**Comment by Kookiness** [comment]
Fantastic! That's great to hear; it would be a massive convenience if you ever manage to implement this. :) Thank you very much!

**Comment by Gerren** [comment]
Implemented in 1.06. It's quite rudimentary, but should do the work. Have fun!
